### ISSUE TITLE
yf.download fails with pandas 2.0.0

### ISSUE THREAD

**Issue by mndavidoff** [ranaroussi/yfinance#1478]
Pandas 2.0.0 was released today. It appears something changed in Pandas that breaks `yf.download`. I'm using:

* Python 3.11.2
* yfinance 0.2.14
* macOS 12.6.4

`yf.download` works with Pandas 1.5.3:

```
>>> import pandas as pd
>>> import yfinance as yf
>>> pd.__version__
'1.5.3'
>>> yf.__version__
'0.2.14'
>>> yf.download('MSFT', start='2023-04-03', end='2023-04-04')
[*********************100%***********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close    Volume
Date
2023-04-03  286.519989  288.269989  283.950012  287.230011  287.230011  24100907
```

`yf.download` fails with Pandas 2.0.0:

```
>>> import pandas as pd
>>> import yfinance as yf
>>> pd.__version__
'2.0.0'
>>> yf.__version__
'0.2.14'
>>> yf.download('MSFT', start='2023-04-03', end='2023-04-04')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- MSFT: No data found for this date range, symbol may be delisted
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

**Comment by Kantubhukta-Hemanth** [comment]
I too got the Same problem. do anyone know how to fix it?

**Comment by alexdgithub** [comment]
It's not pandas, it's the python version. Leaving pandas alone, I switched to 3.10.0 with pyenv. Voila, it works.

**Comment by Kantubhukta-Hemanth** [comment]
May i know how exactly i can do that - "switched to 3.10.0 with pyenv. Voila"

**Comment by alexdgithub** [comment]
You can google pyenv. It has good documentation. 

My findings so far: 

1. With python set to 3.11.2 outside of a an env, opening a python console and running yf.download("SPY") returns "No data found for this date range, symbol may be delisted"
2. Running in a poetry environment with python set to 3.11.2 and running yf.download("SPY") returns "No data found for this date range, symbol may be delisted"
3. With python set to 3.10.0, opening a python console and running yf.download("SPY") returns the dataframe.
4. Running in a poetry environment with python set to 3.10.0 and running yf.download("SPY") returns "No data found for this date range, symbol may be delisted"

**Comment by mndavidoff** [comment]
@alexdgithub,

> It's not pandas, it's the python version. Leaving pandas alone, I switched to 3.10.0 with pyenv.

Your test results and my test results appear to be inconsistent.

1. Both tests in the original report were performed with Python 3.11.2. The only difference in the virtual environments was the version of Pandas.
1. I created two new virtual environments using Python 3.10.10. Download succeeds in the venv using Pandas 1.5.3. Download fails in the venv using Pandas 2.0.0.

I see no difference in the operation of `yf.download` when using Python 3.10 vs. Python 3.11. Perhaps you could double-check the version of Pandas in each of your Python 3.10 venvs?

**Comment by alexdgithub** [comment]
@mndavidoff Indeed it seems i had a global pandas 1.5.3 on the machine. I started with a clean poetry env with 3.10.0 and pandas 2. Doesn't work. Modified .toml to install pandas 1.5.3 and it works.

**Comment by mndavidoff** [comment]
I found the change in Pandas 2.0.0 that broke `yf.download`. Line 654 in `yfinance/base.py` says:

```
dt_now = end_dt.tzinfo.localize(_datetime.datetime.utcnow())
```

This works with Pandas 1.5.3. However, with Pandas 2.0.0, it raises `AttributeError("'datetime.timezone' object has no attribute 'localize'")`. Unfortunately, the exception handler at line 670 of `base.py` silently ignores this error.

In Pandas 1.5.3, `end_dt.tzinfo` is a `pytz.UTC` object. In Pandas 2.0.0, `end_dt.tzinfo` is a `datetime.timezone` object. This incompatible change to the Pandas API is documented at _[UTC and fixed-offset timezones default to standard-library tzinfo objects](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#utc-and-fixed-offset-timezones-default-to-standard-library-tzinfo-objects)_. There might be other issues with Pandas 2.0.0 as well.

**Comment by Kantubhukta-Hemanth** [comment]
@mndavidoff 
Can the problem be solved or is there any other ways to download the stock data rather than using yf.download().
Because my Project has to be submitted within a week.

**Comment by mndavidoff** [comment]
@Kantubhukta-Hemanth, to work around the problem, I suggest you create a Python virtual environment containing Pandas 1.5.3 instead of Pandas 2.0.0.

**Comment by Soel-Philippe** [comment]
@mndavidoff Hope they gonna fix it within a ouple of weeks.

**Comment by ValueRaider** [comment]
_Be the change you want to see_

**Comment by homerokzam** [comment]
I have the same problem!

**Comment by ef1313** [comment]
From my experience the issue appears to be any version of yfinance > 0.1.96.  I've tested all yfinance versions above this using python 3.10.6 and all fail until downgrading yfinance to 0.1.96

**Comment by markqiu** [comment]
#1488  It doesn't work for me.
