### ISSUE TITLE
Issue in getting funds related data after updating to 0.2.54

### ISSUE THREAD

**Issue by kashish590** [ranaroussi/yfinance#2301]
**Mod edit: only reply if `yf.__version__` prints latest version. Ignore PIP Conda etc**

---

### Describe bug

Hi, I'm trying to download funds data using the Funds module. Till 2025-02-18, I was on an older version. The script used to run fine. I switched to a newer version because of rate limit errors which is breaking my current script whenever it encounters a ticker for which it cannot find the data(Error 404). All requests for subsequent tickers result in Attribute error.
Following is the error log:

```
2025-02-19 19:50:00 : 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/?modules=quoteType%2CsummaryProfile%2CtopHoldings%2CfundProfile&corsDomain=finance.yahoo.com&symbol=&formatted=false&crumb=%7B%22finance%22%3A%7B%22result%22%3Anull%2C%22error%22%3A%7B%22code%22%3A%22Unauthorized%22%2C%22description%22%3A%22Invalid+Cookie%22%7D%7D%7D
2025-02-19 19:50:00 : module 'requests.cookies' has no attribute 'clear'
2025-02-19 19:50:00 : module 'requests.cookies' has no attribute 'clear'
2025-02-19 19:50:00 : module 'requests.cookies' has no attribute 'clear'
2025-02-19 19:50:00 : module 'requests.cookies' has no attribute 'clear'
2025-02-19 19:50:00 : module 'requests.cookies' has no attribute 'clear'
2025-02-19 19:50:00 : module 'requests.cookies' has no attribute 'clear'
```

### Simple code that reproduces your problem

```
import yfinance as yf
ticker_holder = yf.Tickers(isin_list)
{k : v.get_funds_data() for k,v in ticker_holder.tickers.items()}
```
```
Case1: isin_list = ['INF209KB1Y49', 'INF846K013E0', 'INF194KB1CL0', 'INF761K01FR0', 'INF955L01AG0', 'INF760K01KO9', 'INF740KA1UC1', 'INF754K01SD8', 'INF179KC1BS5', 'INF336L01QN5', 'INF109K01613', 'INF205K01DN2', 'INF00XX01168', 'INF174KA1HV3', 'INF767K01RK7', 'INF174V01341', 'INF769K01KK8', 'INF204K01489', 'INF966L01614', 'INF200KA18E2', 'INF277KA1679', 'INF582M01IO7', 'INF03VN01803']

Case2 : isin_list = ['INF209K01EN2', 'INF846K01K35', 'INF194KB1AL4', 'INF761K01EP7', 'INF251K01SR5', 'INF760K01JC6', 'INF740K01QD1', 'INF754K01JN6', 'INF090I01569', 'INF179KA1RZ8', 'INF917K01QA1', 'INF109K01BK6', 'INF205K013T3', 'INF00XX01747', 'INF174K01237', 'INF397L01JS1', 'INF174V01BK7', 'INF247L01BY3', 'INF204K01HY3', 'INF663L01W06', 'INF966L01689', 'INF082J01432', 'INF200K01T51', 'INF903J01NK9', 'INF277K011O1', 'INF582M01BU9', 'INF789F1AUQ1']
```

Consider the above two isin lists. If the isin_list in case 1 is run with the above code, it generates an output without an error. When isin_list in case 2 is the input to the above code, the code breaks with the error log mentioned previously. After running isin_list in case2, if you rerun the same code for isin_list in case1, now the code breaks and returns the same error as mentioned in the error log.

### Debug log

part of DEBUG LOG when isin_list in case 2 is executed
```
    557 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P000133SB.BO
    558 DEBUG    Entering get()
    559 DEBUG     Entering _make_request()
    560 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P000133SB.BO
    561 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '0P000133SB.BO', 'formatted': 'false'}
    562 DEBUG      Entering _get_cookie_and_crumb()
    563 DEBUG       cookie_mode = 'basic'
    564 DEBUG       Entering _get_cookie_and_crumb_basic()
    565 DEBUG        reusing cookie
    566 DEBUG        reusing crumb
    567 DEBUG       Exiting _get_cookie_and_crumb_basic()
    568 DEBUG      Exiting _get_cookie_and_crumb()
    569 DEBUG      response code=200
    570 DEBUG     Exiting _make_request()
    571 DEBUG    Exiting get()
    572 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/
    573 DEBUG    Entering get()
    574 DEBUG     Entering _make_request()
    575 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/
    576 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '', 'formatted': 'false'}
    577 DEBUG      Entering _get_cookie_and_crumb()
    578 DEBUG       cookie_mode = 'basic'
    579 DEBUG       Entering _get_cookie_and_crumb_basic()
    580 DEBUG        reusing cookie
    581 DEBUG        reusing crumb
    582 DEBUG       Exiting _get_cookie_and_crumb_basic()
    583 DEBUG      Exiting _get_cookie_and_crumb()
    584 DEBUG      response code=404
    585 DEBUG      toggling cookie strategy basic -> csrf
    586 DEBUG      Entering _get_cookie_and_crumb()
    587 DEBUG       cookie_mode = 'csrf'
    588 DEBUG       Entering _get_crumb_csrf()
    589 DEBUG        csrfToken = 3CcqK1ModoNJALtZ86GQKe2D7zVP71Jb
    590 DEBUG        sessionId='3_cc-session_029f278e-ff03-4056-9603-cdcbe561c029
    591 DEBUG        crumb = '{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}'
    592 DEBUG       Exiting _get_crumb_csrf()
    593 DEBUG      Exiting _get_cookie_and_crumb()
    594 DEBUG      response code=404
    595 DEBUG     Exiting _make_request()
    596 DEBUG    Exiting get()
    597 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/
    598 DEBUG    Entering get()
    599 DEBUG     Entering _make_request()
    600 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/
    601 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '', 'formatted': 'false'}
    602 DEBUG      Entering _get_cookie_and_crumb()
    603 DEBUG       cookie_mode = 'csrf'
    604 DEBUG       Entering _get_crumb_csrf()
    605 DEBUG        reusing crumb
    606 DEBUG       Exiting _get_crumb_csrf()
    607 DEBUG      Exiting _get_cookie_and_crumb()
    608 DEBUG      response code=404
    609 DEBUG      toggling cookie strategy csrf -> basic
    610 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001EQU4.BO
    611 DEBUG    Entering get()
    612 DEBUG     Entering _make_request()
    613 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001EQU4.BO
    614 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '0P0001EQU4.BO', 'formatted': 'false'}
    615 DEBUG      Entering _get_cookie_and_crumb()
    616 DEBUG       cookie_mode = 'csrf'
    617 DEBUG       Entering _get_crumb_csrf()
    618 DEBUG        reusing crumb
    619 DEBUG       Exiting _get_crumb_csrf()
    620 DEBUG      Exiting _get_cookie_and_crumb()
    621 DEBUG      response code=401
    622 DEBUG      toggling cookie strategy csrf -> basic
    623 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001EQU4.BO
    624 DEBUG    Entering get()
    625 DEBUG     Entering _make_request()
    626 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001EQU4.BO
    627 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '0P0001EQU4.BO', 'formatted': 'false'}
    628 DEBUG      Entering _get_cookie_and_crumb()
    629 DEBUG       cookie_mode = 'csrf'
    630 DEBUG       Entering _get_crumb_csrf()
    631 DEBUG        reusing crumb
    632 DEBUG       Exiting _get_crumb_csrf()
    633 DEBUG      Exiting _get_cookie_and_crumb()
    634 DEBUG      response code=401
    635 DEBUG      toggling cookie strategy csrf -> basic
    636 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001J49Z.BO
    637 DEBUG    Entering get()
    638 DEBUG     Entering _make_request()
    639 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001J49Z.BO
    640 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '0P0001J49Z.BO', 'formatted': 'false'}
    641 DEBUG      Entering _get_cookie_and_crumb()
    642 DEBUG       cookie_mode = 'csrf'
    643 DEBUG       Entering _get_crumb_csrf()
    644 DEBUG        reusing crumb
    645 DEBUG       Exiting _get_crumb_csrf()
    646 DEBUG      Exiting _get_cookie_and_crumb()
    647 DEBUG      response code=401
    648 DEBUG      toggling cookie strategy csrf -> basic
    649 DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001J49Z.BO
    650 DEBUG    Entering get()
    651 DEBUG     Entering _make_request()
    652 DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/0P0001J49Z.BO
    653 DEBUG      params={'modules': 'quoteType,summaryProfile,topHoldings,fundProfile', 'corsDomain': 'finance.yahoo.com', 'symbol': '0P0001J49Z.BO', 'formatted': 'false'}
    654 DEBUG      Entering _get_cookie_and_crumb()
    655 DEBUG       cookie_mode = 'csrf'
    656 DEBUG       Entering _get_crumb_csrf()
    657 DEBUG        reusing crumb
    658 DEBUG       Exiting _get_crumb_csrf()
    659 DEBUG      Exiting _get_cookie_and_crumb()
    660 DEBUG      response code=401
    661 DEBUG      toggling cookie strategy csrf -> basic
```
Everything after the first 404 response code has a response code 404 or 401. 

### `yfinance` version

0.2.54

### Python version

3.12.4

### Operating system

Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-130-generic x86_64)

**Comment by kashish590** [comment]
I wasn't facing this issue with the older version though. Tickers which returned a 404 code earlier did not impact data for tickers that are fetched after it. This is peculiar behavior in this version of the library

**Comment by kashish590** [comment]
@ValueRaider just wanted to confirm if this issue is in the pipeline for a fix/being looked at?

**Comment by ValueRaider** [comment]
I'm not aware of anything.

**Comment by JanMkl** [comment]
@kashish590 #2388 is now merged that should fix this issue.

**Comment by kashish590** [comment]
@JanMkl thanks for the fix. It worked
