### PR TITLE
Fix: Restore dev branch regression with Ticker.history()

### PR DESCRIPTION
**Pull request by dhruvan2006**
Fix regression introduced by #2192 that broke the functionality of the `dev` branch while implementing custom periods.

`Ticker.history()` and `download()` methods were broken.

### CODE REVIEW

**Comment by ValueRaider** [comment]
Can you give an example regression?

**Comment by dhruvan2006** [comment]
On `dev` branch:

```python
import yfinance as yf

hist = yf.Ticker("AAPL").history()
print(hist)
```

> Traceback (most recent call last):
>   File "C:\Users\dhruv\yfinance\test.py", line 3, in <module>
>     hist = yf.Ticker("AAPL").history()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dhruv\yfinance\yfinance\utils.py", line 103, in wrapper
>     result = func(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dhruv\yfinance\yfinance\base.py", line 81, in history
>     return self._lazy_load_price_history().history(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dhruv\yfinance\yfinance\utils.py", line 103, in wrapper
>     result = func(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dhruv\yfinance\yfinance\scrapers\history.py", line 109, in history
>     end = utils._parse_user_dt(end, self.tz)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dhruv\yfinance\yfinance\utils.py", line 427, in _parse_user_dt
>     dt = int(dt.timestamp())
>              ^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'timestamp'

**Comment by ValueRaider** [comment]
Thanks.

@R5dan FYI your PR #2192 was broken, and didn't handle custom period strings.

**Comment by R5dan** [comment]
Sorry, should have done more testing. Probably happened when moving functionality from `Ticker.history` to `utils`.
