### ISSUE TITLE
Ticker.history: history's index is not of type DateTimeIndex when dividend and split tables are empty

### ISSUE THREAD

**Issue by ProgrammingDao** [ranaroussi/yfinance#937]
**Issue**:

Ticker.history (line 295):
>       df.index = df.index.tz_localize("UTC").tz_convert(data["chart"]["result"][0]["meta"]["exchangeTimezoneName"])
E       AttributeError: 'Index' object has no attribute 'tz_localize'

**Reason**: 

During the concatenation of a proper price table with empty dividend and split tables, the price table's index has changed from _pandas.DatetimeIndex_ to _pandas.Index_ because the empty tables had this index type.

**Proposed solution**: 

Modify _parse_actions_ (in utils.py) to initialise the dividend and split tables with : 
`dividends = _pd.DataFrame(columns=["Dividends"], index=_pd.DatetimeIndex([]))`
 `splits = _pd.DataFrame(columns=["Stock Splits"], index=_pd.DatetimeIndex([]))`

Local modules' versions:

finance : 0.1.69
pandas : 1.4.0
python : 3.10

**Comment by ProgrammingDao** [comment]
I have found out that the issue occurs when upgrading pandas from 1.3.5 to 1.4.0.

**Comment by bma-diy** [comment]
Thank you for identifying the issue is with numpy. pip install pandas==1.3.5 resolved the issue for me.

Here are the error messages I experienced when using yfinance in a virtual environment:

```
  File "/home/ubuntu/myproject/env/lib/python3.8/site-packages/yfinance/base.py", line 295, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

```
This happens whenever I try to download ticker data with 'period'.

**Comment by psbj** [comment]
Glad this was fixed, but the update isn't on [pip](https://pypi.org/project/yfinance/), it's still at 0.1.69. I'm not familiar with how releases work on pip, is it automated and just takes a while or something else?

**Comment by ProgrammingDao** [comment]
@psbj you need to release a new version with the fix I think. There seems to be a GitHub action to do it. @ranaroussi is it right ?

**Comment by ProgrammingDao** [comment]
@psbj, @ranaroussi has just updated the version and released the version with the fix.

**Comment by keithtmccartney** [comment]
Thank-you so much, I had been bashing my head all weekend over a resolution when trying out Part Time Larry's (@hackingthemarkets) YouTube video "PyAlgoTrade Tutorial (Part 2) - Backtesting Basics" (https://www.youtube.com/watch?v=cdeftn1AZO8). New to Python, been a C# guy for years, this is a whole lot of fun!
