### ISSUE TITLE
get_ticker_by_isin does not takes session parameter

### ISSUE THREAD

**Issue by ydaveluy** [ranaroussi/yfinance#2530]
### Describe bug

It seems to be regression. I have the following error:

  File "/usr/lib/python3.13/site-packages/yfinance/utils.py", line 92, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/yfinance/multi.py", line 131, in download
    ticker = utils.get_ticker_by_isin(ticker, session=session)
TypeError: get_ticker_by_isin() got an unexpected keyword argument 'session'

It works as expected if I remove the session argument at this line:
https://github.com/ranaroussi/yfinance/blob/0eb11c56b00ad8c1174a2fe29b047735c7a2099b/yfinance/multi.py#L131

### Simple code that reproduces your problem

```python
    stock_data:pd.DataFrame = yf.download(tickers="LU1829219390",
        period="1y",
        group_by="ticker")
```

### Debug log from yf.enable_debug_mode()

-

### `yfinance` version

2.62

### Python version

3.13

### Operating system

Linux

**Comment by ydaveluy** [comment]
This issue was introduced by #2514

**Comment by ValueRaider** [comment]
Fix in #2531, was quicker than explaining.

workaround: use `yf.Ticker`
