### ISSUE TITLE
repair=True can rescale an entire price table by 100x and invert the Repaired? flags

### ISSUE THREAD

**Issue by lenamonj** [ranaroussi/yfinance#2924]
### Describe bug

When `_fix_unit_switch` detects a genuine unit change affecting part of a price table, the correction is applied to the **whole** table, and the `Repaired?` flag array is inverted wholesale rather than being restricted to the affected block.

On a GBp-quoted table containing one genuine 100x block:

- all 90 rows come back 100 times too large
- the 20 genuinely broken rows are flagged `Repaired? = False`
- 40 untouched rows are flagged `Repaired? = True`
- a control run with that branch skipped returns 0 of 90 rows wrong

Three further defects surfaced in the same area:

1. `history.py` calls `to_numpy()` and then writes in place, raising `ValueError: assignment destination is read-only` on pandas 3.0.5. Your own committed fixture `tests/data/SSNLF-1d-bad-div.csv` triggers this.
2. The crude 100x fallback rescales OHLC but not `Adj Close`; default `auto_adjust` then reapplies the factor.
3. A fund paying capital gains with no dividend on the same day hits a `ZeroDivisionError`.

I have a patch covering all four. Against your 42 committed golden fixtures it leaves 41 byte-identical and fixes the one that currently raises. Happy to open a PR.

(Refiling: my earlier report was auto-closed for not using this form. Same content, correct template.)

### Simple code that reproduces your problem

This runs fully offline and never contacts Yahoo, so it is deterministic and not affected by rate limiting:

```python
import numpy as np, pandas as pd
from yfinance.scrapers.history import PriceHistory

idx = pd.date_range("2024-01-02", periods=90, freq="B", tz="Europe/London")
df = pd.DataFrame({c: np.full(90, 100.0) for c in ["Open","High","Low","Close","Adj Close"]}, index=idx)
df["Volume"] = 1000
df["Dividends"] = 0.0
df["Stock Splits"] = 0.0

# one genuine block quoted in the other unit
df.iloc[20:40, :5] *= 100.0

# the state _standardise_currency() leaves behind for a GBp ticker
ph = PriceHistory(None, "TEST.L", "Europe/London")
ph._history_metadata = {"currency": "GBP", "exchangeTimezoneName": "Europe/London",
                        "currencyRepaired": True}

out = ph._fix_unit_switch(df.copy(), "1d", "Europe/London")

wrong = (out["Close"] > 1000).sum()
print("rows returned 100x too large:", wrong, "of", len(out))
print("Repaired? True on the genuinely broken rows 20:40 :", out["Repaired?"].iloc[20:40].sum())
print("Repaired? True on untouched rows 40:80 :", out["Repaired?"].iloc[40:80].sum())
```

*(edited: the original paste dropped the metadata and Dividends/Stock Splits setup lines - this version runs as pasted)*

Observed: 90 of 90 rows too large, 0 of the broken rows flagged, 40 untouched rows flagged.

### Debug log with debug logging enabled

Not applicable in the usual form: the reproduction above drives the repair functions directly with a fixture frame and makes no network calls, so there is no Yahoo request/response traffic to log. The defect is in the repair arithmetic, not in fetching. With `yf.config.debug.logging = True` set, the run emits no fetch entries, only the repair path.

### `yfinance` version

1.5.2 (HEAD `beac22d981ab37362a70c9e4e49261ac622acbe4`)

### Python version

3.13.8, pandas 3.0.5, numpy 2.5.1, scipy 1.18.0

### Operating system

Windows 11

**Comment by ValueRaider** [comment]
I can't run your code - `_fix_unit_switch` is trying to access undefined class members e.g.

```
    if self._history_metadata['currency'] == 'KWF':
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PriceHistory' object has no attribute '_history_metadata'. Did you mean: 'get_history_metadata'?
```

That's not the only error.

Try dev branch, there are repair improvements.

**Comment by lenamonj** [comment]
You're right, and I apologise. That snippet could never have run. It builds the object with `PriceHistory.__new__` and sets no attributes, and the frame is missing `Dividends` and `Stock Splits`. It was reduced from a working harness and I did not re-run the reduced version before posting. That wasted your time and it shouldn't have happened.

Here is one that does run. Self-contained and offline, and it works on both 1.5.2 and dev - `_standardise_currency` returns 2 values on 1.5.2 and 4 on dev, so this indexes rather than unpacks.

```python
import numpy as np, pandas as pd, yfinance as yf
from yfinance.scrapers.history import PriceHistory

tz, n = "Europe/London", 90
rng = np.random.default_rng(11)
close = 50.0 * np.cumprod(1 + rng.normal(0, 0.01, n))
idx = pd.DatetimeIndex([pd.Timestamp.now(tz=tz).normalize() - pd.Timedelta(days=n-1-i) for i in range(n)])
true_gbp = close.copy()

df = pd.DataFrame(index=idx)
for c in ["Open","High","Low","Close","Adj Close"]:
    df[c] = close
df["Volume"], df["Dividends"], df["Stock Splits"] = 1000, 0.0, 0.0

price_cols = ["Open","High","Low","Close","Adj Close"]
df[price_cols] *= 100.0                                                # served in pence
df.iloc[40:60, [df.columns.get_loc(c) for c in price_cols]] *= 100.0   # genuine 100x block

ph = PriceHistory(None, "TEST.L", tz)
ph._history_metadata = {"currency": "GBp", "exchangeTimezoneName": tz,
                        "regularMarketPrice": float(df["Close"].iloc[-1])}

r = ph._standardise_currency(df.copy(), "GBp")
d1, cur = r[0], r[1]
ph._history_metadata["currency"] = cur
d2 = ph._fix_unit_switch(d1, "1d", tz)

got, flags = d2["Close"].to_numpy(), d2["Repaired?"].to_numpy()
print(f"yfinance {yf.__version__}")
print(f"rows wrong after repair: {int((np.abs(got/true_gbp - 1) > 0.01).sum())} of {n}")
print(f"Repaired? on the 20 broken rows 40:60: {int(flags[40:60].sum())} of 20")
print(f"Repaired? on the 40 untouched rows 0:40: {int(flags[:40].sum())} of 40")
```

On dev at `a81e012` I get the same as on 1.5.2:

```
rows wrong after repair: 90 of 90
Repaired? on the 20 broken rows 40:60: 0 of 20
Repaired? on the 40 untouched rows 0:40: 40 of 40
```

I checked the others against dev too, since you asked. The `ValueError: assignment destination is read-only` in `_fix_bad_div_adjust` is **fixed on dev** - that one is gone, so ignore it. The `ZeroDivisionError` in `_repair_capital_gains`, when a fund pays capital gains with no dividend on the same day, still reproduces on dev.

The offer of a PR stands if it is useful.

**Comment by ValueRaider** [comment]
Is there any way to provide the ticker symbols?

**Comment by lenamonj** [comment]
Not directly, and I should be straight about why: the reproduction is synthetic on purpose. The defect is in the arithmetic after the bad state exists, so a deterministic offline fixture shows it without depending on what Yahoo happens to be serving that week. That also means I cannot point you at a ticker exhibiting the combined state live today.

The two halves of the state are each grounded in real tickers, though:

- The subunit-currency table: XDEV.L, from #2866 - my fixture transcribes the pence values the reporter printed there.
- A genuine partial 100x block inside a table: your own committed fixtures, `tests/data/AET-L-1d-100x-error.csv` and `SSW-JO-1d-100x-error.csv`.

The finding is the composition of the two: a subunit-quoted table that also carries a real 100x block. Once both hold, the whole-table rescale and the flag inversion follow deterministically from the code path, which is what the snippet above drives.

For the capital-gains `ZeroDivisionError`: any fund distributing a capital gain with no dividend on the same date reaches it. I do not have a verified live ticker and date to hand you, but the state fits your fixture format, and the PR I offered would carry fixture-based tests in the same style as your 100x-error CSVs, so nothing in it would depend on live data. Happy to build it that way if that works for you.

**Comment by ValueRaider** [comment]
Understood. Go ahead with the PR. Include a unit test with test csv data - I can understand better with table in a spreadsheet.

**Comment by lenamonj** [comment]
PR is up: #2927. Fixture-based as discussed - the two CSV tables in tests/data open directly in a spreadsheet, one for the partial-block case and one proving the d3704c8 revert still fires where it should.
