### ISSUE TITLE
yfinance 0.2.1 - 'Ticker' object has no attribute 'quarterly_financials'

### ISSUE THREAD

**Issue by galashour** [ranaroussi/yfinance#1259]
Used to work with 0.1.94, but seems to be missing in 0.2.1:

  File "C:\Data\Python\Pumba\Pumba_fetch_data.py", line 657, in get_ticker_data
    df_quarterly_financials = ticker_data.quarterly_financials
AttributeError: 'Ticker' object has no attribute 'quarterly_financials'
